Issue 56
hlxsites/airlessco pull request #113
Opened 2023-02-08 21:35 UTC by venturewise

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #56 

Test URLs:
- Before: https://main--airlessco--hlxsites.hlx.page/emea/cz/products/accessories/
- After: https://issue-56--airlessco--hlxsites.hlx.page/emea/cz/products/accessories/

2023-02-08 22:04 UTC, bstopp requested changes

2023-02-08 22:04 UTC, bstopp commented on blocks/productcards/productcards.js
> +  const accessoriesTitle = document.querySelector('h1');
This breaks when the document is not the accessories card. Check the console log of this page:

https://issue-56--airlessco--hlxsites.hlx.page/na/en/products/

2023-02-08 22:04 UTC, bstopp commented on blocks/productcards/productcards.css
> +  font-weight: bold;
why "bold" and not a numerical value?

2023-02-08 22:26 UTC, bstopp commented
Also, the change breaks the product landing page's width setting - compare:

https://issue-56--airlessco--hlxsites.hlx.page/na/en/products/

2023-02-09 01:47 UTC, venturewise commented on blocks/productcards/productcards.css
> +  font-weight: bold;
changed to 700

2023-02-09 01:47 UTC, helms-charity commented on blocks/productcards/productcards.js
> +  const accessoriesTitle = document.querySelector('h1');
Moved to accessories-details

2023-02-09 17:14 UTC, bstopp approved these changes

2023-02-09 17:23 UTC, merged